//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePatient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Erkrankungens
    {
        public int Id_Erkrankung { get; set; }
        public string Erkrankung { get; set; }
        public Nullable<System.DateTime> Wann { get; set; }
        public string Chronisch { get; set; }
        public int Pat_Medi_DataId_Pat_Medi_Data { get; set; }
    
        public virtual Pat_Medi_Datas Pat_Medi_Datas { get; set; }
    }
}
