//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePatient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medikations
    {
        public int Id_Medikation { get; set; }
        public string Medikament { get; set; }
        public string Art { get; set; }
        public string Dosis { get; set; }
        public string Einnahmeregel { get; set; }
        public string Besonderheit { get; set; }
        public Nullable<System.DateTime> Wann { get; set; }
        public int Pat_Medi_DataId_Pat_Medi_Data { get; set; }
    
        public virtual Pat_Medi_Datas Pat_Medi_Datas { get; set; }
    }
}
