//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePatient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notfallkontakte
    {
        public int Id_Notfallkontakte { get; set; }
        public string Vorname { get; set; }
        public string Name { get; set; }
        public string Telefonnummer { get; set; }
        public string Strasse { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public int PatientsId_Patient { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
