//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePatient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notfallaktions
    {
        public int Id_Nottaktion { get; set; }
        public string Aktion { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Straße { get; set; }
        public Nullable<short> Nr { get; set; }
        public Nullable<short> PLZ { get; set; }
        public string Ort { get; set; }
        public string Telefon { get; set; }
        public string Besonderheit { get; set; }
        public int PatientId_Patient { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
