//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePatient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pat_Medi_Datas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pat_Medi_Datas()
        {
            this.Allergiens = new HashSet<Allergiens>();
            this.Dokumentes = new HashSet<Dokumentes>();
            this.Erkrankungens = new HashSet<Erkrankungens>();
            this.Medikations = new HashSet<Medikations>();
        }
    
        public int Id_Pat_Medi_Data { get; set; }
        public Nullable<bool> Organspende { get; set; }
        public Nullable<bool> Patfafü { get; set; }
        public Nullable<bool> Betreuungsverfügung { get; set; }
        public int PatientId_Patient { get; set; }
        public bool Sorgerechtsverfügung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allergiens> Allergiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokumentes> Dokumentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Erkrankungens> Erkrankungens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medikations> Medikations { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
