//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePatient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Arzts = new HashSet<Arzts>();
            this.Notfallaktions = new HashSet<Notfallaktions>();
            this.Notfallkontakte = new HashSet<Notfallkontakte>();
            this.Pat_Medi_Datas = new HashSet<Pat_Medi_Datas>();
        }
    
        public int Id_Patient { get; set; }
        public string Anrede { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Straße { get; set; }
        public Nullable<short> Nr { get; set; }
        public Nullable<short> PLZ { get; set; }
        public string Ort { get; set; }
        public string geb { get; set; }
        public string ort_geb { get; set; }
        public string Telefon { get; set; }
        public string Krankenkasse { get; set; }
        public string KrankenkassenNR { get; set; }
        public string PersonalausweisNR { get; set; }
        public string FührerscheinNR { get; set; }
        public byte[] Image { get; set; }
        public int LoginId_Login { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arzts> Arzts { get; set; }
        public virtual Logins Logins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notfallaktions> Notfallaktions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notfallkontakte> Notfallkontakte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pat_Medi_Datas> Pat_Medi_Datas { get; set; }
    }
}
